// ============================================================
// Shared helpers for building responsive <img> markup from the
// width variants generated by scripts/resize-images.py.
//
// Every photo in images/rooms and images/property has -480w,
// -900w and -1600w variants (a few smaller source photos only
// got the widths smaller than their original size -- that's
// why each entry in the data files lists its own `widths`).
// ============================================================

function buildSrcset(basePath, widths) {
  return widths.map((w) => `${basePath}-${w}w.jpg ${w}w`).join(', ');
}

/**
 * Returns an <img> tag string with srcset/sizes wired up.
 * @param {object} photo - { image, widths, alt }
 * @param {object} [options] - { className, sizes, loading }
 */
function responsiveImg(photo, options = {}) {
  const {
    className = 'photo-cover',
    sizes = '(max-width: 700px) 100vw, 400px',
    loading = 'lazy',
  } = options;

  const widths = photo.widths || [480, 900, 1600];
  const largest = widths[widths.length - 1];
  const fallbackSrc = `${photo.image}-${largest}w.jpg`;
  const srcset = buildSrcset(photo.image, widths);

  return `<img class="${className}" src="${fallbackSrc}" srcset="${srcset}" sizes="${sizes}" alt="${photo.alt}" loading="${loading}" decoding="async">`;
}

// ---- Shared scroll-reveal observer ----
// Defined here (loaded first) so data-driven renderers
// (rooms.js, gallery.js, guide.js) can observe elements they
// create, and main.js can reuse the same observer for any
// reveal elements already present in a page's static HTML.
const revealObserver = new IntersectionObserver(
  (entries) => {
    entries.forEach((entry) => {
      if (entry.isIntersecting) {
        entry.target.classList.add('is-visible');
        revealObserver.unobserve(entry.target);
      }
    });
  },
  { threshold: 0.15 }
);
